version: 0.2

phases:
  install:
    runtime-versions:
        php: 7.3
        nodejs: 12
  pre_build:
    commands:
      - echo Running Pre-Build script...
      - echo pre build started on `date`
      - echo `pwd`
  build:
    commands:
      - echo `pwd`
      - echo Running Build...
      - npm install
      - composer install
  post_build:
    commands:
      - echo Running post_build...
      - echo Build completed on `date`
artifacts:
    files: "**/*"