version: 0.2

phases:
  install:
    runtime-versions:
        php: 7.3
        nodejs: 12
  pre_build:
    commands:
      - echo Running Pre-Build script...
      - echo pre build started on `date`
  build:
    commands:
      - echo Build started on this `date` 
      - pwd
      - ls
      - cd ./themes/musi
      - pwd
      - npm install
      - composer install
  post_build:
    commands:
      - echo Running post_build...
      - echo Build completed on `date`
artifacts:
    files: "**/*"